=> Your service is live ðŸŽ‰
==> 
==> ///////////////////////////////////////////////////////////
==> 
==> Available at your primary URL https://www.laplumbprep.com + 2 more domains
==> 
==> ///////////////////////////////////////////////////////////
12:32:17 AM [express] GET /api/auth/me 401 in 3ms :: {"message":"Not authenticated"}
12:32:17 AM [express] GET /api/enrollments 401 in 1ms :: {"message":"Not authenticated"}
Error seeding database: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      error: [Function],
      message: [Function],
      close: [Function],
      open: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'arraybuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://dpg-cup8uppopnds739241hg-a.oregon-postgres.render.com/v2',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ETIMEDOUT 35.227.164.209:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '35.227.164.209',
    port: 443
  },
  [Symbol(kMessage)]: 'connect ETIMEDOUT 35.227.164.209:443'
}
Database unavailable, serving fallback course data
12:34:32 AM [express] GET /api/courses 200 in 134997ms :: [{"id":"louisiana-journeyman-prep","title":â€¦
12:34:36 AM [express] GET /api/products 500 in 132975ms :: {"message":"connect ETIMEDOUT 35.227.164.2â€¦
12:34:36 AM [express] GET /api/products/featured 500 in 132951ms :: {"message":"connect ETIMEDOUT 35.â€¦
Error initializing email campaigns: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      error: [Function],
      message: [Function],
      close: [Function],
      open: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'arraybuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://dpg-cup8uppopnds739241hg-a.oregon-postgres.render.com/v2',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ETIMEDOUT 35.227.164.209:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '35.227.164.209',
    port: 443
  },
  [Symbol(kMessage)]: 'connect ETIMEDOUT 35.227.164.209:443'
}
12:36:51 AM [express] GET /api/products/featured 500 in 134288ms :: {"message":"connect ETIMEDOUT 35.â€¦
12:36:51 AM [express] GET /api/products 500 in 134213ms :: {"message":"connect ETIMEDOUT 35.227.164.2â€¦
==> Detected service running on port 10000
==> Docs on specifying a port: https://render.com/docs/web-services#port-binding
Error initializing bulk enrollment tiers: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      error: [Function],
      message: [Function],
      close: [Function],
      open: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'arraybuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://dpg-cup8uppopnds739241hg-a.oregon-postgres.render.com/v2',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: connect ETIMEDOUT 35.227.164.209:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '35.227.164.209',
    port: 443
  },
  [Symbol(kMessage)]: 'connect ETIMEDOUT 35.227.164.209:443'
}
12:38:33 AM [express] Email automation system initialized
12:38:33 AM [express] Bulk pricing system initialized
12:43:54 AM [express] GET /api/auth/me 401 in 1ms :: {"message":"Not authenticated"}
12:43:59 AM [express] GET /api/enrollments 401 in 1ms :: {"message":"Not authenticated"}
12:44:02 AM [express] GET /api/auth/me 401 in 1ms :: {"message":"Not authenticated"}
12:44:02 AM [express] GET /api/enrollments 401 in 1ms :: {"message":"Not authenticated"}